name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
